---
# Picture handling 
PIC_DIR : "/home/pi/Pictures" # directory where to find the pictures
SUBDIRECTORY : ""    # (optional) subdir of pic_dir - can be changed by MQTT
CHECK_DIR_TM : 600.0  # time in seconds between checking if the image directory has changed
DATE_FROM : None      # Sets start date [y,m,d] of the timerange for the fotos you want to show (None=unlimited)
DATE_TO : None        # Sets end date [y,m,d] of the timerange for the fotos you want to show (None=unlimited)
RECENT_DAYS : 90      # If set to > 0, images which were created within the last N days are shown (supersedes DATE_FROM)
OUTDATED_FILE_PROP : 0.005  # Include outdated images with this propability (0.0=disable)
PROP_SLOPE : 180       # Propability to select files outside [date_from, date_to] slowly decreases to from 1 to OUTDATED_FILE_PROP within this number of days
NO_FILES_IMG : "no-pictures.jpg"  # image to show if none selected
DIR_CACHE_FILE : ".dir_cache.p" # Directory cache file 
PIC_EXT :  # Include files with these file extensions
  - '.png'
  - '.jpg'
  - '.jpeg'
  - '.heif'
  - '.heic'
IGNORE_DIRS :    # Ignore images if they are in one of those directories
  - '.AppleDouble'
  - '@eaDir'
  - '#snapshot'
  - 'Backup'
  - 'Archive'
  - 'Archiv'
  - 'Zeitlos'
  - 'Public'

# Shader 
FIT : True          # shrink to fit screen i.e. don't crop
BLUR_AMOUNT : 12.0   # larger values than 12 will increase processing load quite a bit
BLUR_EDGES : False   # use blurred version of image to fill edges - will override FIT : False
BLUR_ZOOM : 1.0      # must be >= 1.0 which expands the backgorund to just fill the space around the image
EDGE_ALPHA : 0.3     # background colour at edge. 1.0 would show reflection of image")
FPS : 20.0           # granularity of blending
BACKGROUND : [0.2, 0.2, 0.3, 1.0] # RGBA to fill edges when fitting
SHADER : "blend_new"
KENBURNS : False     # Use Kenburns effect; it set to True: will set FIT->False and BLUR_EDGES->False
AUTO_RESIZE : True   # set this to False if you want to use 4K resolution on Raspberry Pi 4. You should ensure your images are the correct size for the display
BLEND_TYPE : 0.0     # choose between ["blend":0.0, "burn":1.0, "bump:2.0"]; type of blend the shader can do
BLEND_OPTIONS : {"blend":0.0, "burn":1.0, "bump":2.0} # that work with the blend_new fragment shader (better don't change!)

# Shuffle
SHUFFLE : True        # shuffle on reloading image files - can be changed by MQTT
RESHUFFLE_NUM : 1     # no of loops before reshuffling
RECENT_N : 0          # when shuffling the keep n most recent ones to play before the rest
TIME_DELAY : 30.0     # Defines how long a single slide is shown - can be changed by MQTT
FADE_TIME : 3.0       # change time during which slides overlap 
INFO_TXT_TIME : 25.0  # duration for showing text overlay over image 

# Text overlay
TEXT_FORMAT : 
  - "<flen> (<flen35>) <exp> <fnum> <iso> <artist>"  # Header line 1 
  - "<rating> <desc>"                                # Header line 2
  - "<date> <gps>"                                   # Footer line 1
  - "<path>/<file>"                                  # Footer line 2

TEXT_POINT_SIZE : 55    # Text size
RESOLVE_GPS : True      # Resolve GPS coordinates in EXIF 

# Options
VERBOSE : True      # show debug messages
KEYBOARD : False     # set to False when running headless to avoid curses error. True for debugging
FONT_FILE : "NotoSans-Regular.ttf"
DELAY_EXIF : True    # set this to false if there are problems with date filtering - it will take a long time for initial loading if there are many images!
CODEPOINTS : '1234567890AÄBCDEFGHIJKLMNOÖPQRSTUÜVWXYZ.,!* _-/:;@()°%abcdefghijklmnñopqrstuvwxyzäöüß' # valid text characters 

# MQTT
MQTT_SERVER : "localhost"   # Just change if you want to use a different MQTT server
MQTT_PORT : 1883            # Just change if you want to use a different MQTT server
MQTT_LOGIN  : " "           # Just change if you want to use a different MQTT server
MQTT_PASSWORD : ""          # Just change if you want to use a different MQTT server  
MQTT_TOPIC : "screen"       # MQTT topic name (top-level); just change if you e.g. run multiple infotainment screens  

# Infotainment
INFO_SKIP_CNT : 15          # show infotainment screen after each N pictures (=0 disables infotainment sceen)
WEATHER_REFRESH_DELAY : 300 # refresh weather info every N seconds
PV_REFRESH_DELAY : 30       # refresh weather info every N seconds

# Infotainment - Weather
W_LATITUDE : 48.9           # latitude of your location (decimal degrees, e.g. 48.12345)
W_LONGITUDE : 12.1          # longitude of your location (decimal degrees, e.g. 11.98765)
W_UNIT : "metric"           # metric 
W_LANGUAGE : "de"           # language
W_API_KEY : "YOUR API KEY"  # openweathermap API key for "One Call API" 
W_ICON_DIR : "icons"        # weather icon directory
W_BACK_IMG : "weather_back_16_9.jpg"   # background image for weather info 
W_POINT_SIZE : 80           # weather text size
W_STATIC_SIZE : 75          # size of static images (temp, humidity, wind, ...)
W_ICON_SIZE : 200           # size of weather forecast icons (sunny, cloudy, ...) 
W_MARGIN_LEFT : 30          # left margin 
W_MARGIN_TOP : 75           # top margin
W_SPACING : 80              # spacing between the weather columns

#RKI COVID
RKI_ID : 00000              # RKI region ID; you can find out here: https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data
RKI_REGION : "Bayern"       # Bundesland

# PV MQTT server
MQTT_PV_SERVER : "xxxxxxxxx"   # MQTT server IP or name
MQTT_PV_PORT : 1883            # Server port
MQTT_PV_LOGIN  : " "           # Login
MQTT_PV_PASSWORD : ""          # Password  
MQTT_PV_TOPIC : "MYTOPIC"      # Topic you want to listen to

# Infotainment - PV Info
PV_INFO_ENABLE : False      # Enable / disable PV info screen
PV_ICON_DIR : "icons"       # PV icon director
PV_BACK_IMG : "PV_background_16_9.png"   # background image for PV info 
PV_POINT_SIZE : 80          # PV text size
PV_MARGIN_LEFT : 30         # left margin 
PV_MARGIN_TOP : 75          # top margin

# CAMERA
CAMERA_ZOOM : 0.75          # zoom level for vlc player (e.g. shrink or enlarge video)
CAMERA_URL : "URL"          # URL of webcam stream, e.g. "rtsp://<user>:<pw>@<ip-address>:<port>/<path>"
CAMERA_THRESHOLD : 30       # threshold for the camera viewer. Defines how long viewer will be displayed after a MQTT event

# Monitor schedule
# One line per day: 0=Monday ... 6=Sunday
# For each day you can define an array of start-stop time pairs 
# Monitor schedule
# weekday: 0=Monday ... 6=Sunday
# For each day you can define multiple pairs of start-stop times [HH,MM]
MONITOR_SCHEDULE : 
  0: 
    - [[07,00], [22,30]] 
  1: 
    - [[07,00], [22,30]] 
  2: 
    - [[07,00], [22,30]] 
  3: 
    - [[07,00], [22,30]] 
  4: 
    - [[07,00], [23,30]] 
  5: 
    - [[07,00], [23,30]] 
  6: 
    - [[07,00], [23,30]] 

# Infoserver (Webserver) config
SRV_ROOT : "srvroot"
PIC_HISTORY : 15     # Length of the picture history to be shown in web UI

# RCT Power device
RCT_SERVER : "192.168.178.32"
RCT_PORT : 8899
